name: ci

on:
  push:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Run deploy script on GCE
        run: |-
          gcloud beta compute ssh --quiet --zone "europe-west2-c" "instance-1" --project "${{ secrets.GCP_PROJECT_ID }}"
          pm2 delete index
          git pull
          npm i
          pm2 start src/index.js